pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

variables:
  GOROOT: '/usr/local/go1.12'
  GOPATH: '$(system.defaultWorkingDirectory)/work'
  sdkPath: '$(GOPATH)/src/github.com/$(build.repository.name)'

steps:
- script: |
    set -e
    mkdir -p '$(GOPATH)/bin'
    mkdir -p '$(sdkPath)'
    shopt -s extglob
    mv !(work) '$(sdkPath)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    echo '##vso[task.prependpath]$(GOPATH)/bin'
  displayName: 'Create Go Workspace'
- script: |
    curl -sSL https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    dep ensure -v
    go install ./vendor/golang.org/x/lint/golint
  workingDirectory: '$(sdkPath)'
  displayName: 'Install Dependencies'
- script: |
    grep -L -r --include *.go --exclude-dir vendor -P "Copyright (\d{4}|\(c\)) Microsoft" ./ | tee /dev/stderr | test -z "$(< /dev/stdin)"
    test -z "$(gofmt -s -l -w ./autorest/. | tee /dev/stderr)"
    test -z "$(golint ./autorest/... |  tee /dev/stderr)"
  workingDirectory: '$(sdkPath)'
  displayName: 'Formatting and Linting'
- script: |
    go vet ./autorest/...
    go build -v ./autorest/...
  workingDirectory: '$(sdkPath)'
  displayName: 'Vet and Build'
- script: |
    go test -race -v ./autorest/...
  workingDirectory: '$(sdkPath)'
  displayName: 'Run Tests'
